package com.kbph.logistics.om.domain;

import com.kbph.logistics.common.domain.CommonColumnDTO;

import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

@Getter
@Setter
@ToString
public class WshpitDTO extends CommonColumnDTO{
	private String shpdcky;
	private Integer shpdcit;
	private String warekey;
	private String shpitst;
	private String poshpdt;
	private String poshptm;
	private String poshpdy;
	private String doccate;
	private String doctype;
	private String outboky;
	private Integer outboit;
	private String oubrqdt;
	private String oubrqtm;
	private String speidat;
	private String speitim;
	private String btrcate;
	private String ownerky;
	private String ownrnam;
	private String custcod;
	private String custnam;
	private String fncusky;
	private String fcnamlc;
	private String skugrky;
	private String skumkey;
	private String skudesc;
	private Double skuthic;
	private Double skuwidt;
	private Integer skuleng;
	private Integer skuweig;
	private Double grosswd;
	private Integer grossln;
	private Integer grosswg;
	private Double grossth;
	private String frareky;
	private String frlocky;
	private Integer frlayer;
	private String shlocky;
	private String regiorg;
	private String regimod;
	private String destorg;
	private String destmod;
	private String demodyn;
	private String demdman;
	private String demdadr;
	private String dempocd;
	private String demdtln;
	private String stlotnb;
	private String purcnum;
	private String orderln;
	private String itemcod;
	private String shplimt;
	private String delvdsr;
	private String btrfstc;
	private String obomemo;
	private String allgrky;
	private Integer rgitqty;
	private Integer shalqty;
	private Integer shcfqty;
	private String suomkey;

	private String taskoky;
	private String shpplky;
	private String whnamlc;
	private String docctnm;
	private String doctynm;
	private String vhcfnam;
	private String vonamlc;
	private String drvernm;
	private String rsncdnm;
	private String tstsnam;
	private String areanam;
	private String locanam;
	private String shlcnam;
	private String rgorgnm;
	private String deorgnm;
	private String rgmodnm;
	private String demodnm;
	private String shpdcst;
	private String rcvdcdt;
	private String rcvdctm;
	private String rcvdcky;
	private Integer rcvdcit;
	private String frlocnm;
	private String frarenm;
	private String tskstnm;
	private String grpkynm;
	private String reorgnm;
	private String remodnm;
	private String addcoky;
	private String stkstat;
	private String stkmemo;
	private String lotat01;
	private String lotat02;
	private String lotat03;
	private String addcnam;
	private String btrcnam;
	private String emskuyn;
	private String equipky;
	private String shpsday;
	private String shpstim;
	private String spehdat;
	private String spehtim;
	private String vhplnky;
}
